[tool.poetry]
name = "tveq"
version = "0.2.0"
description = ""
authors = ["Simon Kowallik <sk-github@simonkowallik.com>"]

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1"
plotly = "^6"
requests = "^2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
